export { SettingPage } from './src/main/ets/view/SettingPage';
export { MinePage } from './src/main/ets/view/MinePage';
export { OnlineSearchPageBuilder, SearchRouteParam } from './src/main/ets/view/OnlineSearchPage';
export { ArtistDetailPage, ArtistDetailPageBuilder } from './src/main/ets/view/ArtistDetailPage';
export { AlbumDetailPage, AlbumDetailPageBuilder } from './src/main/ets/view/AlbumDetailPage';

export { AccountManageSheet } from "./src/main/ets/account/AccountManageSheet";
export { PlatformMusicPageBuilder } from "./src/main/ets/account/PlatformMusicPage";

